### ISSUE TITLE
Self-distances

### ISSUE THREAD

**Issue by lhudson08** [Denes-Lab/ClustFinder#3]
RDK: is it necessary to keep instances where self distance is recorded? it seems like removing them would save resources and prevent many clusters of size 1

**Comment by lhudson08** [comment]
- [x] @harleenkchaggar: test with dataset with added self-comparisons

**Comment by harleenkchaggar** [comment]
Incorporated several genomes into the input pairwise.tsv file and also added a code in ClustFinder to generate a .tsv file named self-dist.tsv. This file will contain the genomes that have self-comparisons. ClustFinder is functioning as expected, correctly identifying and incorporating these  self-comparing genomes into that file.
