### ISSUE TITLE
Potential issue with cat

### ISSUE THREAD

**Issue by lhudson08** [Denes-Lab/ClustFinder#4]
RDK: the cat command on line 272 can become stuck and write out an enormous, hard-drive filling file if the merge file contains only one cluster
    - cat $files_to_merge >> "$outfile"
    - this will recursively write to the cluster file if files_to_merge is the same name as outfile
    - this happened when I accidentally input a space separated file in place of a TSV
    - Recommend catching the behavior earlier and seeing if it can be caused by other means (is a space-separated file the only possible way this can happen?)

**Comment by lhudson08** [comment]
### @harleenkchaggar add tests:
- [x] input file exists
- [x] input file is tsv
- [x] input file has at least 2 lines
- [x] input file has numbers in the third column
- [x] input file has blank line at the bottom; if not, add that line
- [x] threshold is a number

**Comment by harleenkchaggar** [comment]
Tested all checked scenarios and ClustFinder works as intended.
